# Generated by Django 6.0.5 on 2026-05-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=20)),
                ('normalized_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('lock_status', models.CharField(choices=[('unlocked', 'Unlocked'), ('locked', 'Locked')], default='unlocked', max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='ingestion.rawrecord')),
            ],
            options={
                'verbose_name': 'Normalized Record',
                'verbose_name_plural': 'Normalized Records',
            },
        ),
    ]
