# Generated by Django 6.0.5 on 2026-05-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='ingestion_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('normalized', 'Normalized')], default='uploaded', max_length=20),
        ),
    ]
