# Generated by Django 6.0.5 on 2026-05-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_datasource_ingestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='ingestion_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('validated', 'Validated'), ('normalized', 'Normalized'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
