# Generated by Django 6.0.5 on 2026-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_alter_datasource_ingestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='ingestion_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('VALIDATED', 'Validated'), ('NORMALIZED', 'Normalized'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20),
        ),
    ]
